# Generated by Django 4.2.6 on 2023-10-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('counts', models.IntegerField(default=0)),
                ('last_retrieve_car', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=100)),
                ('scraping_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarRecomender.scrapingreport')),
            ],
        ),
    ]
