# Generated by Django 4.2.5 on 2023-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRecomender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carprediction',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
